### ISSUE TITLE
False Positive &#8211; preg_replace()  /e modifier

### ISSUE THREAD

**Issue by octalmage** [wpengine/phpcompat#115] opened 2017-02-27 15:13 UTC
False Positive &ndash; preg_replace() &ndash; /e modifier<br>
http://ift.tt/2lXXT2s<br><p>Replies: 0</p>
<p>We&rsquo;re seeing this error:</p>
<p><code>ERROR | preg_replace() &ndash; /e modifier is deprecated since PHP 5.5 and removed since PHP 7.0</code></p>
<p>But, our code isn&rsquo;t using a /e modifier. It does however include an &ldquo;e&rdquo; in the regex. Please take a look at this thread.</p>
<p><a href="http://ift.tt/2lJAzW9" rel="nofollow">http://ift.tt/2lJAzW9</a></p>
<p>Thanks!</p>
<br><br>
via WordPress.org Forums &raquo; [PHP Compatibility Checker] Support http://ift.tt/2gps7Vy<br>
February 27, 2017 at 09:02AM

**Comment by jrfnl** [comment] 2017-02-27 15:55
This should be fixed once https://github.com/wimg/PHPCompatibility/pull/357 has been merged.

The issue was *not* caused by the regex using an `e` in the regex itself, but by the regex being delimited with quotes (seriously?!?!).

**Closed** 2018-07-24 22:20 UTC
