### ISSUE TITLE
Specify Plugin/Path to test against

### ISSUE THREAD

**Issue by jag1989** [wpengine/phpcompat#216] opened 2018-12-13 14:16 UTC
Would it be possible to add an instruction to the CLI where a specific plugin/path could just be tested? 

I.e I've made some changes/updates to a plugin, I'd like to run the tool again to confirm there are no errors.

`wp phpcompat 7.2 plugin=pluginname`

**Comment by Julix91** [comment] 2020-02-04 19:44
Duplicate of https://github.com/wpengine/phpcompat/issues/67

**Comment by mindctrl** [comment] 2020-02-04 20:49
Thanks for bring this up. Let's continue the conversation on #67.

**Closed by mindctrl** 2020-02-04 20:49 UTC
