### ISSUE TITLE
Fatal error during scan - Undefined method

### ISSUE THREAD

**Issue by Gkrab** [wpengine/phpcompat#249] opened 2019-10-17 20:37 UTC
[17-Oct-2019 20:20:29 UTC] PHP Fatal error:  Call to undefined method PHPCompatibility\Sniffs\Operators\RemovedTernaryAssociativitySniff::isShortTernary() in /websites/petraregoort.nl/vrijheid/wp-content/plugins/php-compatibility-checker/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniffs/Operators/RemovedTernaryAssociativitySniff.php on line 125

WP 5.2.4 
PHP 5.6.40

**Comment by jrfnl** [comment] 2019-10-17 21:40
Duplicate of #245

**Closed** 2019-10-18 16:33 UTC
