### ISSUE TITLE
Fatal error during scan???

### ISSUE THREAD

**Issue by kenw232** [wpengine/phpcompat#247] opened 2019-09-06 10:13 UTC
Why do I get this error when I do a scan?  How do I fix it?

core(/home/site): wp phpcompat 7.2 --scan=active
Testing compatibility with PHP 7.2.

Fatal error: Call to undefined method PHPCompatibility\PHPCSHelper::findStartOfStatement() in /home/user/public_html/site.com/site/wp-content/plugins/php-compatibility-checker/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniffs/FunctionUse/ArgumentFunctionsReportCurrentValueSniff.php on line 323
Error: The site is experiencing technical difficulties.

**Comment by jrfnl** [comment] 2019-09-06 12:34
Duplicate of #245

**Closed** 2019-09-09 13:37 UTC
